---

extends:
#  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
plugins:
  - babel
  - jsx-a11y
rules:
  quotes: [1, "double", "avoid-escape"]
  semi: ["error", "always"]
  no-console: 0
  no-trailing-spaces: 0
  babel/new-cap: 1
  babel/no-invalid-this: 1
  babel/object-curly-spacing: 1

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
parser: babel-eslint
env:
  node: true
  es6: true
  browser: true
